apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
type: Opaque
stringData:

  {{- if not (hasKey .Values "config") -}}
  {{- $_ := set .Values "config" dict -}}
  {{- end -}}

  {{/* SETUP CONFIG */}}
  {{ range $key, $value := .Values.config }}
  {{ upper $key}}: {{ quote $value }}
  {{ end }}
